### PR TITLE
Added a favicon and made little changes in buttons

### PR DESCRIPTION
**Pull request by roli25**
solved issue number #6

### CODE REVIEW

**Comment by tejaswini22199** [comment]
please put before and after pictures.

**Comment by roli25** [comment]
Screenshot (183)
Screenshot (184)

**Comment by roli25** [comment]
Screenshot (187)
Screenshot (188)

**Comment by tejaswini22199** [comment]
remove that favicon it was not needed in this project and changing button color is very small change.

**Pull request closed without merging**
