### PR TITLE
Updation

### PR DESCRIPTION
**Pull request by Navpreet1234**
#### Put x if you followed:
[]Doc Update
[]New feature
[]Bug fix
[]Code Enhancement
[]Are you uptodate with base repository
[]Followed contribution guidelines
[]Did you check in your local machine if the functionality you added is working or not
fixes #your issue number
before and after screenshots

### CODE REVIEW

**Comment by tejaswini22199** [comment]
did you do all the changes and pls update readme

**Comment by Navpreet1234** [comment]
Yes mami didi. One dark mode created and another display forks wala issue
both.
Aaj boht mushkil se issue resolve hua merese.

**Comment by Navpreet1234** [comment]
Mam***   did***

Sry for inconvenience.

**Comment by tejaswini22199** [comment]
Readme was not updated.😅

**Comment by Navpreet1234** [comment]
I am updating it. Dont wry. Issue mujhe conflicts resolve mai boht hora tha
toh I was engaged into it plus clg exams are going on so kaafi pressure
hogya tha waise hi.

**Comment by tejaswini22199** [comment]
that's okay do it at your own pace but try to do it because students who try to solve other issues may get conflicts.

**Pull request merged**
