### PR TITLE
Changes in UI using css

### PR DESCRIPTION
**Pull request by Navpreet1234**
#### Put x if you followed:
[]Doc Update
[]New feature
[]Bug fix
[]Code Enhancement
[]Are you uptodate with base repository
[]Followed contribution guidelines
[]Did you check in your local machine if the functionality you added is working or not
fixes #your issue number
before and after screenshots

### CODE REVIEW

**Comment by tejaswini22199** [comment]
@Navpreet1234  pls add screenshots of before and after

**Comment by Navpreet1234** [comment]
Screenshot (49)
Screenshot (50)
Screenshot (51)

**Comment by Navpreet1234** [comment]
@tejaswini22199 is this fine???

**Comment by tejaswini22199** [comment]
@Navpreet1234  the background is not good previous one is better i guess

**Comment by Navpreet1234** [comment]
@tejaswini22199 Can u plz tell what changes are required ??

**Comment by tejaswini22199** [comment]
hey pls try other issues to be frank The present UI is fine.

**Comment by Navpreet1234** [comment]
ok fine.

**Comment by Navpreet1234** [comment]
But I think pictures are looking fine.

**Comment by tejaswini22199** [comment]
Its looking clumsy. Website needs to be simple and clean

**Pull request closed without merging**
