### PR TITLE
Updation of readme and added webdev resources Patch 1

### PR DESCRIPTION
**Pull request by Navpreet1234**
#### Put x if you followed:
[]Doc Update
[]New feature
[]Bug fix
[]Code Enhancement
[]Are you uptodate with base repository
[]Followed contribution guidelines
[]Did you check in your local machine if the functionality you added is working or not
fixes #your issue number
before and after screenshots

### CODE REVIEW

**Comment by tejaswini22199** [comment]
hey you did not update readme with proper image urls. Pls check them @Navpreet1234

**Comment by Navpreet1234** [comment]
Can u send me pics of what u r getting bcoz I'm able to see the pictures on
my pc.

**Comment by tejaswini22199** [comment]
https://github.com/tejaswini22199/KnowledgeShare
@Navpreet1234  check this link once try opening in incognito mode. I cannot see images in readme.md.

**Comment by Navpreet1234** [comment]
Yrr check the readme once, you will se that the links of images are
working if you open them on any other tab but i dont know why images are
not getting shown. Aap ek baar check krlo khud.

**Comment by tejaswini22199** [comment]
ks
Please be patient while you are a student or contributor. It is your responsibility to do correct changes. and look at this file.

**Comment by Navpreet1234** [comment]
I think we should see 1-2 days more bcoz mereko aaj aur bhi issue boht aare
hai code mai but last 2 days ago nhi aare the nd I was able to see pictures
in readme.
I'm trying to solve this.

**Comment by Navpreet1234** [comment]
Hii i have updated readme.
Sent u pull rqst.
Also checked in incognito mode and this is working now👍👍.

**Pull request merged**
