### PR TITLE
Create a file for collating all the ideas related to new features and enhancements

### PR DESCRIPTION
**Pull request by Godzilla5111**
Solves Issue #3 .

### CODE REVIEW

**Comment by Godzilla5111** [comment]
Hey @tejaswini22199, please review the changes and merge the PR if satisfied👍 Cheers!✌

**Comment by tejaswini22199** [comment]
use bullet points to refer to each idea

**Comment by Godzilla5111** [comment]
I have used numbers, is it ok now? @tejaswini22199 ?

**Comment by Godzilla5111** [comment]
Thanks✌

**Pull request merged**
