### PR TITLE
Remove Item button added

### PR DESCRIPTION
**Pull request by Nivedita967**
Solved issue #2 .
Added an option to delete the entire row by clicking a button.

### CODE REVIEW

**Comment by tejaswini22199** [comment]
Hey @Nivedita967  could you put a screenshot of what its removing, like a small video would be great

**Comment by Nivedita967** [comment]
https://www.loom.com/share/1ac058c4a1db4affba0e01707bb63cb0

**Comment by Nivedita967** [comment]
https://www.loom.com/share/12a70c858131488b8b82b815957b7d64

**Comment by tejaswini22199** [comment]
So yeah you were deleting the whole list in the local storage but I want a button at the end of each row. Whenever a user clicks the button only one row has to be deleted.

**Comment by tejaswini22199** [comment]
Don't remove this functionality this is also helpful but along with this add the above one too.

**Comment by Nivedita967** [comment]
Okay, No Problem, I will add that as well.

**Comment by Nivedita967** [comment]
Hey, I am not able to implement that functionality. So, please assign it another.
If you want you can merge the clear whole list functionality.

**Comment by Nivedita967** [comment]
Thank You.

**Pull request merged**
