### PR TITLE
add-clearlist

### PR DESCRIPTION
**Pull request by archana-1209**
issue #2

### CODE REVIEW

**Comment by tejaswini22199** [comment]
Please follow PR template. Add screenshots or video if necessary ki how it is removing that single item.

**Comment by archana-1209** [comment]
Do we need to remove a single row at once or the entire list at once?
Capture
this is removing entire list at once!

**Comment by tejaswini22199** [comment]
single row

**Comment by archana-1209** [comment]
ok I will work on it

**Comment by archana-1209** [comment]
Capture
I have added the additional feature to delete a single row of the list too.
Can I create a PR?

**Comment by tejaswini22199** [comment]
hey @archana-1209  there are some conflicts in the style.css folder. Please resolve them.

**Comment by archana-1209** [comment]
ok!!

**Comment by archana-1209** [comment]
I have made the required  changes and solved the conflicts.

**Pull request merged**
