### PR TITLE
Add Favicon, Prettify code

### PR DESCRIPTION
**Pull request by Godzilla5111**
Added a suitable favicon and successfully resolved Issue #7 .

### CODE REVIEW

**Comment by Godzilla5111** [comment]
Please review the changes @tejaswini22199 , and merge the PR if satisfied👍. Thanks😃

**Comment by tejaswini22199** [comment]
Please include screenshot of your page so that it is easy to know what changes you made, while you are making a pull request

**Comment by Godzilla5111** [comment]
Which page are you referring to @tejaswini22199 ? I didn't get it..

**Comment by tejaswini22199** [comment]
@Godzilla5111  what is the additional functionality this issue issolving,  I did not get it you just added a favicon but where did you use.

**Comment by Godzilla5111** [comment]
I have used it in book.html @tejaswini22199 . Please check.
image

**Comment by tejaswini22199** [comment]
hey @Godzilla5111  this favicon is not needed in this project so I don't think this issue is valid. So I'm closing the issue

**Pull request closed without merging**
