### PR TITLE
changed background color and button color 

### PR DESCRIPTION
**Pull request by roli25**
for #6 issue

### CODE REVIEW

**Comment by tejaswini22199** [comment]
hey pls add before and after ss

**Comment by roli25** [comment]
Screenshot_193
Screenshot_194

**Comment by roli25** [comment]
@tejaswini22199  is this fine?

**Comment by tejaswini22199** [comment]
pls update readme.md ill merge it then

**Comment by roli25** [comment]
done! @tejaswini22199

**Pull request merged**
